const { contextBridge, ipcRenderer, shell } = require('electron');

contextBridge.exposeInMainWorld('electron', {
    openExternal: (url) => shell.openExternal(url),
    send: (channel, data) => ipcRenderer.send(channel, data),
    on: (channel, func) => ipcRenderer.on(channel, (event, ...args) => func(...args)),
    getDetections: () => ipcRenderer.invoke('app:get-detections'),
    getHealth: () => ipcRenderer.invoke('app:get-health'),
    retryQueue: () => ipcRenderer.invoke('app:retry-queue'),
    fullDiagnostics: () => ipcRenderer.invoke('app:full-diagnostics'),
    restartDiscord: () => ipcRenderer.invoke('app:restart-discord'),
    askAI: (query) => ipcRenderer.invoke('app:ask-ai', query),
    runPcSupport: () => ipcRenderer.invoke('app:pc-support'),
    simulateAlert: () => ipcRenderer.invoke('app:simulate-alert'),
    runCleaner: (options = {}) => ipcRenderer.invoke('app:run-cleaner', options), // FIX #3: invoke (no send) para activar ipcMain.handle
    registerUser: (user, pass) => ipcRenderer.invoke('auth:register', { user, pass }),
    loginUser: (user, pass) => ipcRenderer.invoke('auth:login', { user, pass }),
    forgotPassword: (email) => ipcRenderer.invoke('auth:forgot-password', { email }),
    resetPassword: (token, newPassword) => ipcRenderer.invoke('auth:reset-password', { token, newPassword }),
    minimizeWindow: () => ipcRenderer.send('window:minimize'),
    maximizeWindow: () => ipcRenderer.send('window:maximize'),
    closeWindow: () => ipcRenderer.send('window:close'),
    adminAction: (type, targetId) => ipcRenderer.send('admin:action', { type, targetId }),
    getServerInfo: () => ipcRenderer.invoke('app:get-server-info'),
    enterpriseStatus: () => ipcRenderer.invoke('enterprise:get-status'),
    enterpriseSendEvent: (payload) => ipcRenderer.invoke('enterprise:send-event', payload),
    enterpriseVersionCheck: () => ipcRenderer.invoke('enterprise:version-check'),
    enterpriseFlushQueue: () => ipcRenderer.invoke('enterprise:flush-backend-queue'),
    enterpriseAnalyze: (type, payload) => ipcRenderer.invoke('enterprise:ai-analyze', { type, payload }),
    enterpriseRepairInspect: () => ipcRenderer.invoke('enterprise:repair-inspect'),
    enterpriseRepairPreviewClean: () => ipcRenderer.invoke('enterprise:repair-preview-clean'),
    enterpriseAnticheatStart: () => ipcRenderer.invoke('enterprise:anticheat-start'),
    enterpriseAnticheatHeartbeat: () => ipcRenderer.invoke('enterprise:anticheat-heartbeat'),
    enterpriseAnticheatSimulateEvent: () => ipcRenderer.invoke('enterprise:anticheat-simulate-event'),
    enterpriseGuardGameStart: () => ipcRenderer.invoke('enterprise:guard-game-start'),
    enterpriseSSStatus: (status) => ipcRenderer.invoke('enterprise:ss-status', status),
    enterpriseSSPrepareLogs: () => ipcRenderer.invoke('enterprise:ss-prepare-logs'),
    enterpriseDiscordTicket: (type) => ipcRenderer.invoke('enterprise:discord-ticket', type),
    enterpriseExportReport: () => ipcRenderer.invoke('enterprise:export-report'),
    licenseStatus: () => ipcRenderer.invoke('license:get-status'),
    activateLicense: (payload) => ipcRenderer.invoke('license:activate', payload),
    clearLicenseCache: () => ipcRenderer.invoke('license:clear-cache'),
    getProductPlans: () => ipcRenderer.invoke('product:get-plans')
});
